apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: todoapp
  labels:
    app: todo-backend
    tier: backend
data:
  CORS_ORIGINS: "http://todo-frontend:3000,http://localhost:3000,http://localhost:8000"
