apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: todoapp
  labels:
    app: todo-backend
    tier: backend
spec:
  type: NodePort
  selector:
    app: todo-backend
    tier: backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30801
    protocol: TCP
    name: http
